export const ALL_DEPARTMENTS = [
  "All Departments",
  "Artificial Intelligence and Data Science",
  "Electronics and Communication Engineering",
  "Electrical and Electronics Engineering",
  "Information Technology",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Electronics and Instrumentation Engineering",
  "Integrated Computer Science and Engineering",
  "Mechanical and Automation Engineering",
  "Mechanical Engineering",
  "Computer Science and Business System",
  "AIML",
  "ANY",
  "Computer and Communication Engineering",
  "Instrumentation and Control Engineering",
  "Cyber Security",
  "Internet of Things",
];
