export const COMMUNITIES = ["OC", "BC", "BCM", "MBC", "SC", "ST", "SCA"];

export const INDIAN_STATES = [
  { id: 1, state: "Andhra Pradesh" },
  { id: 2, state: "Arunachal Pradesh" },
  { id: 3, state: "Assam" },
  { id: 4, state: "Bihar" },
  { id: 5, state: "Chhattisgarh" },
  { id: 6, state: "Delhi" },
  { id: 7, state: "Goa" },
  { id: 8, state: "Gujarat" },
  { id: 9, state: "Haryana" },
  { id: 10, state: "Himachal Pradesh" },
  { id: 11, state: "Jammu & Kashmir" },
  { id: 12, state: "Jharkhand" },
  { id: 13, state: "Karnataka" },
  { id: 14, state: "Kerala" },
  { id: 15, state: "Maharashtra" },
  { id: 16, state: "Madhya Pradesh" },
  { id: 17, state: "Manipur" },
  { id: 18, state: "Meghalaya" },
  { id: 19, state: "Mizoram" },
  { id: 20, state: "Nagaland" },
  { id: 21, state: "Odisha" },
  { id: 22, state: "Punjab" },
  { id: 23, state: "Rajasthan" },
  { id: 24, state: "Sikkim" },
  { id: 25, state: "Tamil Nadu" },
  { id: 26, state: "Tripura" },
  { id: 27, state: "Telangana" },
  { id: 28, state: "Uttar Pradesh" },
  { id: 29, state: "Uttarakhand" },
  { id: 30, state: "West Bengal" },
  { id: 31, state: "Andaman & Nicobar (UT)" },
  { id: 32, state: "Chandigarh (UT)" },
  { id: 33, state: "Dadra & Nagar Haveli (UT)" },
  { id: 34, state: "Daman & Diu (UT)" },
  { id: 35, state: "Lakshadweep (UT)" },
  { id: 36, state: "Puducherry (UT)" },
];
